//crear personas
POST https://smartpol-4605a3e3849e.herokuapp.com/people
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInJvbGUiOiJMSURFUiIsImlhdCI6MTY5NDMwODM5OX0.Jcli7we3zbkpJWiMwqctA3A5R4gQR6jUefF50A5nURI

{
	"identificationNumber": "1102365222",
	"name": "Sandra",
	"lastName": "Villareal",
	"cellPhone": "",
	"phone": "",
	"departamentId": "20",
	"municipalityId": "767",
	"neighborhood": "2",
	"sidewalk": "4",
	"address": "1234",
	"birthdate": "2023-10-09",
	"email": "sandra.villareal@example.com",
	//"leaderId": "2",
	//"candidate": "4",
	"votePlace": "Escuela ABC",
	"gender": "M",
	"bloodType": "O+",
	"occupation": "Engineer",
	"profession": "Software Developer",
	"population": "Urban",
	"academicProfile": "Bachelor's degree in Computer Science",
	"description": "A tech enthusiast and problem solver",
	"observations": "Allergic to peanuts",
	"politicalState": "Neutral",
	"role": "Digitador"
}

###
//obtener departamentos
GET https://smartpol-4605a3e3849e.herokuapp.com/departaments
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwicm9sZSI6IlBST1BJRVRBUklPIiwiY2FtcGFpZ25JZCI6bnVsbCwiaWF0IjoxNzI2ODg1MTg4LCJleHAiOjE3MjY5NzE1ODh9.yD4Z797NtpG-qVBuVCXmAXWdwKfJTryqEMd62dLtqko

###
//obtener municipios
GET https://smartpol-4605a3e3849e.herokuapp.com/municipalities/20
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInJvbGUiOiJMSURFUiIsImlhdCI6MTY5NDMwODM5OX0.Jcli7we3zbkpJWiMwqctA3A5R4gQR6jUefF50A5nURI

###
//obtener lideres
GET https://smartpol-4605a3e3849e.herokuapp.com/users/role/lider
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInJvbGUiOiJMSURFUiIsImlhdCI6MTY5NDMwODM5OX0.Jcli7we3zbkpJWiMwqctA3A5R4gQR6jUefF50A5nURI

###
//obtener persona por identificacion
GET https://smartpol-4605a3e3849e.herokuapp.com/people/identification/1101365487
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInJvbGUiOiJMSURFUiIsImlhdCI6MTY5NDMwODM5OX0.Jcli7we3zbkpJWiMwqctA3A5R4gQR6jUefF50A5nURI

###
//obtener persona por Id
GET https://smartpol-4605a3e3849e.herokuapp.com/people/5
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInJvbGUiOiJMSURFUiIsImlhdCI6MTY5NDMwODM5OX0.Jcli7we3zbkpJWiMwqctA3A5R4gQR6jUefF50A5nURI


###
//Login
POST https://smartpol-4605a3e3849e.herokuapp.com/auth/login
content-type: application/json

{
	"username": "71385323",
	"password": "71385323"
}

###

//filter
GET https://smartpol-4605a3e3849e.herokuapp.com/people/find/filter?leaderId&gender=F&politicalState
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInJvbGUiOiJDQU5ESURBVE9fUFJJTkNJUEFMIiwiY2FtcGFpZ25JZCI6IjEiLCJpYXQiOjE2OTU0OTc2ODgsImV4cCI6MTY5NTU4NDA4OH0.rA9N-OhEXQsfeMD2FIRa76E4-tgCyGQsodGMk2ZMNCM

###

//Export excel
GET https://smartpol-4605a3e3849e.herokuapp.com/people/export/excel?leaderId&gender=F&politicalState
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInJvbGUiOiJDQU5ESURBVE9fUFJJTkNJUEFMIiwiY2FtcGFpZ25JZCI6IjEiLCJpYXQiOjE2OTU0OTc2ODgsImV4cCI6MTY5NTU4NDA4OH0.rA9N-OhEXQsfeMD2FIRa76E4-tgCyGQsodGMk2ZMNCM

###
//Local Environment

POST http://127.0.0.1:2020/auth/login
content-type: application/json

{
	"username": "71385323",
	"password": "71385323"
}