const ROLES_OBJECT = {
    PROPIETARIO: 'PROPIETARIO',
    ADMINISTRADOR: 'ADMINISTRADOR',
    DIGITADOR: 'DIGITADOR',
    LIDER: 'LIDER',
    VOTANTE: 'VOTANTE',
    CANDIDATO: 'CANDIDATO',
    CANDIDATO_PRINCIPAL: 'CANDIDATO_PRINCIPAL',
};

//ROLES A LOS QUE SE LES DEBE CREAR UN USUARIO AL CREAR PERSONA
const ROLES_ARRAY = [
   // 'PROPIETARIO',
    'ADMINISTRADOR',
    'DIGITADOR',
    'LIDER'
];

export { ROLES_OBJECT, ROLES_ARRAY };